openapi: "3.1.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
components:
  schemas:
    PetMax:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          maximum: 13
          format: int64
        name:
          type: string
        tag:
          type: string
